version: '3.4'

services:
  samba:
    build: image
    image: sambinha:1.0
    container_name: sambinha
    user: root
    secrets:
      - samba-secret
    networks:
      - default
    ports:
      - 137:137/udp
      - 138:138/udp
      - 139:139/tcp
      - 445:445/tcp
    read_only: false
    tmpfs:
      - /tmp
    stdin_open: true
    tty: true
    volumes:
      - /mnt:/media
    command: >-
      bash -c '
      sambinha user add username --secret /run/secrets/samba-secret ;
      sambinha share dir media --path /media --writeable yes --valid-users username --browseable yes ;
      service smbd start ;
      tail -F /var/log/samba/log.smbd
      '

secrets:
  samba-secret:
    file: .secret-samba.yml