version: '3.4'

services:
  samba:
    build: image
    image: sambinha:latest
    container_name: sambinha
    user: root
    secrets:
      - secret-config
    networks:
      - default
    ports:
      - 137:137/udp
      - 138:138/udp
      - 139:139/tcp
      - 445:445/tcp
    read_only: false
    tmpfs:
      - /tmp
    stdin_open: true
    tty: true
    volumes:
      - /Users/fernando/Downloads:/media
    command: "start --yml /run/secrets/secret-config"

secrets:
  secret-config:
    file: .secret-config.yml